# Generated by Django 5.1.3 on 2025-06-13 19:11

import apps.administrador.models
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, default='logos/default_logo.png', help_text='Logo del negocio. Solo se permiten archivos JPG, JPEG y PNG.', max_length=255, null=True, verbose_name='imagen')),
                ('direccion_principal', models.CharField(max_length=150)),
                ('direccion_secundaria', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(help_text='El teléfono debe tener exactamente 10 dígitos.', max_length=10, validators=[apps.administrador.models.validate_telefono])),
                ('correo', models.EmailField(max_length=254)),
                ('pagina_web', models.URLField(blank=True, null=True)),
                ('redes_sociales', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
