# Generated by Django 5.1.3 on 2025-06-13 19:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='Sin dirección', max_length=255)),
                ('fecha_hora_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_unidades', models.PositiveIntegerField(default=1)),
                ('costo_total', models.FloatField()),
                ('fecha_fin_reserva', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_planificada', models.TimeField(blank=True, null=True)),
                ('hora_fin_real', models.TimeField(blank=True, null=True)),
                ('calificacion_cliente', models.IntegerField(blank=True, null=True)),
                ('calificacion_negocio', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.combo')),
                ('servicio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
        ),
    ]
